### ISSUE TITLE
Portfolios » 

### ISSUE THREAD

**Issue by CGSGIN4** [hivemindhq/portfolios#67]
### Download for your portfolio

https://drive.google.com/file/d/1Ywv1y6XT8Tx4-W6AC57Y77_1pfovIXsU/view?usp=sharing

### Award Type

Control

### Award Ranking

1

### Field of award

Regional

### Team Name

PML30 North Wind

### Team Number

9746

### Team Region

Russia

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by polargh** [comment]
Added! Thank you for contributing :)
